name: Build sing-box for MacOS


on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
#     strategy:
#       matrix:
#         goos: [linux,darwin]
#         goarch: [amd64]

    runs-on: macos-latest
    env:
#       GOOS: ${{matrix.goos}}
#       GOARCH: ${{matrix.goarch}}
      TAGS: with_clash_api,with_quic,with_grpc,with_wireguard,with_gvisor
#       CGO_ENABLED: 0

    steps:
      - name: check out repo
        uses: actions/checkout@v3
        with:
          repository: SagerNet/sing-box
          path: sing-box
          ref: dev
          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      - name: build
        run: |
          cd sing-box
          go build -v -o /tmp/sing-box -trimpath -tags ${TAGS} -ldflags "-w -s -buildid=" ./cmd/sing-box
          cd /tmp
          sudo curl -sL https://git.io/file-transfer | sh 
          echo "uploading sing-box file"
          wetrans=$(./transfer wet -s -p 16 --no-progress sing-box)
          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          echo "Download URL: $wetrans" >> download.txt
          
      - name: echo download URL
        run: |
          cd /tmp
          cat download.txt

          
          



