# This is a basic workflow to help you get started with Actions

name: build sing-box

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - name: install
        run: |
          git clone -b dev https://github.com/SagerNet/sing-box.git
          cd sing-box
          go build -v -trimpath -tags 'with_clash_api,with_quic' -ldflags "-X 'github.com/sagernet/sing-box/constant.Commit=$(git rev-parse HEAD)' -w -s -buildid=" ./cmd/sing-box
          ls -l
          sudo mkdir tmp
          sudo cp sing-box tmp/
          cd /tmp
          ls -l
          #sudo cp /home/runner/go/bin/sing-box .
          ./sing-box version

      - name: upload file
        run: |
          pwd
          ls -l sing-box
          #sudo curl -sL https://git.io/file-transfer | sh 
          #wetrans=$(./transfer wet -s -p 16 --no-progress sing-box)
          #wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          #echo $wetrans 


